### ISSUE TITLE
ValueError when running the script

### ISSUE THREAD

**Issue by 2xdcreative** [Kocarus/Manga-Translator-TesseractOCR#2]
I get the following error when running the OCR:

Traceback (most recent call last):
  File "E:/Programming/Python/OCR/Manga-Translator-TesseractOCR-master/manga_translate.py", line 67, in <module>
    main()
  File "E:/Programming/Python/OCR/Manga-Translator-TesseractOCR-master/manga_translate.py", line 25, in main
    blurbs = locate_bubbles.get_blurbs(img)
  File "E:\Programming\Python\OCR\Manga-Translator-TesseractOCR-master\locate_bubbles.py", line 47, in get_blurbs
    im2, contours, hierarchy = cv2.findContours(img_gray,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by 2xdcreative** [comment]
Just removed im and im2 from the list and it went through, but now I have the following issue:

Traceback (most recent call last):
  File "E:/Programming/Python/OCR/Manga-Translator-TesseractOCR-master/manga_translate.py", line 67, in <module>
    main()
  File "E:/Programming/Python/OCR/Manga-Translator-TesseractOCR-master/manga_translate.py", line 30, in main
    typeset.typeset_blurb(needTransImg, translated)
  File "E:\Programming\Python\OCR\Manga-Translator-TesseractOCR-master\typeset.py", line 67, in typeset_blurb
    flowed = flow_into_box(text, blurb.w, usingFont)
  File "E:\Programming\Python\OCR\Manga-Translator-TesseractOCR-master\typeset.py", line 25, in flow_into_box
    next_token = text.find(" ", idx + 1)
TypeError: argument should be integer or bytes-like object, not 'str'


and if I replace the " " with any integer I get the following:
Traceback (most recent call last):
  File "E:/Programming/Python/OCR/Manga-Translator-TesseractOCR-master/manga_translate.py", line 67, in <module>
    main()
  File "E:/Programming/Python/OCR/Manga-Translator-TesseractOCR-master/manga_translate.py", line 30, in main
    typeset.typeset_blurb(needTransImg, translated)
  File "E:\Programming\Python\OCR\Manga-Translator-TesseractOCR-master\typeset.py", line 67, in typeset_blurb
    flowed = flow_into_box(text, blurb.w, usingFont)
  File "E:\Programming\Python\OCR\Manga-Translator-TesseractOCR-master\typeset.py", line 30, in flow_into_box
    c_width = text_width(c_text)
  File "E:\Programming\Python\OCR\Manga-Translator-TesseractOCR-master\typeset.py", line 13, in text_width
    return d.textsize(l, font=font)[0]
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\ImageDraw.py", line 318, in textsize
    return font.getsize(text, direction, features)
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\ImageFont.py", line 162, in getsize
    size, offset = self.font.getsize(text, direction, features)
TypeError: expected string

Edit: corrected the paste

**Comment by Banhammer151** [comment]
Which opencv version are you using?

**Comment by ABeater** [comment]
My Input:
`C:\Users\l0calh0st\Desktop\Manga\Manga-Translator-TesseractOCR-master>py -2.7 manga_translate.py`

 Error Output:
```
Processing images:
01.jpg
02.jpg
03.jpg
04.jpg
05.jpg
06.jpg
07.jpg
08.jpg
09.jpg
10.jpg
JAPANESE -> VIETNAMESE
Traceback (most recent call last):
  File "manga_translate.py", line 67, in <module>
    main()
  File "manga_translate.py", line 25, in main
    blurbs = locate_bubbles.get_blurbs(img)
  File "C:\Users\l0calh0st\Desktop\Manga\Manga-Translator-TesseractOCR-master\locate_bubbles.py", line 47, in get_blurbs
    im2, contours, hierarchy = cv2.findContours(img_gray,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
ValueError: need more than 2 values to unpack
```

opencv Version:  4.1.1.26

**Comment by Banhammer151** [comment]
> My Input:
> `C:\Users\l0calh0st\Desktop\Manga\Manga-Translator-TesseractOCR-master>py -2.7 manga_translate.py`
> 
> Error Output:
> 
> ```
> Processing images:
> 01.jpg
> 02.jpg
> 03.jpg
> 04.jpg
> 05.jpg
> 06.jpg
> 07.jpg
> 08.jpg
> 09.jpg
> 10.jpg
> JAPANESE -> VIETNAMESE
> Traceback (most recent call last):
>   File "manga_translate.py", line 67, in <module>
>     main()
>   File "manga_translate.py", line 25, in main
>     blurbs = locate_bubbles.get_blurbs(img)
>   File "C:\Users\l0calh0st\Desktop\Manga\Manga-Translator-TesseractOCR-master\locate_bubbles.py", line 47, in get_blurbs
>     im2, contours, hierarchy = cv2.findContours(img_gray,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
> ValueError: need more than 2 values to unpack
> ```
> 
> opencv Version: 4.1.1.26

Downgrade your opencv version to 2.x.x.x

**Comment by shah0994** [comment]
I'm having this same issue and have not been successful in determining how I can downgrade opencv to 2.x.x.x. I tried using solutions here (https://stackoverflow.com/questions/44439443/python-how-to-pip-install-opencv2-with-specific-version-2-4-9), but didn't work out. Any suggestions?

**Comment by Banhammer151** [comment]
Use python 2

**Comment by Banhammer151** [comment]
> I'm having this same issue and have not been successful in determining how I can downgrade opencv to 2.x.x.x. I tried using solutions here (https://stackoverflow.com/questions/44439443/python-how-to-pip-install-opencv2-with-specific-version-2-4-9), but didn't work out. Any suggestions?

I’ll redownload it after work and give you a full example

**Comment by shah0994** [comment]
That'd be great if you could. I'm hopeful to get this working! Thank you!

**Comment by Banhammer151** [comment]
From what I’ve seen it has a long way to go. I don’t have time to actually work on it but I’ll create a walkthrough for those who need it.

**Comment by shah0994** [comment]
That's fair- if you create a walkthrough, I'd love to see it!

**Comment by usagi123** [comment]
Currently running python 2.7.17 and opencv 2.4.13.7
Got the same error as ABeater. Any thought?

> C:\Users\maiph\Desktop\Manga-Translator-TesseractOCR>python manga_translate.py
Processing images:
01.jpg
02.jpg
03.jpg
04.jpg
05.jpg
06.jpg
07.jpg
08.jpg
09.jpg
10.jpg
JAPANESE -> VIETNAMESE
Traceback (most recent call last):
  File "manga_translate.py", line 67, in <module>
    main()
  File "manga_translate.py", line 25, in main
    blurbs = locate_bubbles.get_blurbs(img)
  File "C:\Users\maiph\Desktop\Manga-Translator-TesseractOCR\locate_bubbles.py", line 47, in get_blurbs
    im2, contours, hierarchy = cv2.findContours(img_gray,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
ValueError: need more than 2 values to unpack

**Comment by Pastaficionado** [comment]
Apparently findContour changed at some point in v3.x.x.x. The ValueError comes from trying to assign 2 values returned from cv2.findContour to 3 locations. I couldn't even find a pre v3.1.0.0, so I stuck with the most recent version and simply changed the following in locate_bubbles.py:
`im2, contours, hierarchy = cv2.findContours(img_gray,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)`
to:
`contours, hierarchy = cv2.findContours(img_gray,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)`
and 
`im2, contours2, hierarchy = cv2.findContours(mask,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)`
to:
`contours2, hierarchy = cv2.findContours(mask,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)`

I also had a separate issue with pytesseract accessing my path, so I had to add:
`pytesseract.pytesseract.tesseract_cmd = 'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'`
near the top of the page.

On my first few tests, the translation quality is noticibly worse than the samples shown, but that's likely because of Tesseract.
